export const PAKISTAN_STATE_CITIES = [
  {
    state: 'Punjab',
    cities: [
      'Ahmadpur East', 'Alipur', 'Arifwala', 'Attock',
      'Bahawalnagar', 'Bahawalpur', 'Basirpur', 'Bhalwal', 'Bhakkar', 'Bhera', 'Burewala',
      'Chakwal', 'Chak Jhumra', 'Chichawatni', 'Chiniot', 'Chishtian', 'Chunian',
      'Darya Khan', 'Daska', 'Dera Ghazi Khan', 'Dipalpur', 'Dunyapur',
      'Faisalabad', 'Fazilpur', 'Ferozewala', 'Fortabbas',
      'Gakhar Mandi', 'Garh Maharaja', 'Gogera', 'Gojra', 'Gujar Khan', 'Gujranwala', 'Gujrat',
      'Hafizabad', 'Harunabad', 'Hasilpur', 'Haveli Lakha',
      'Isa Khel',
      'Jalalpur Pirwala', 'Jampur', 'Jaranwala', 'Jhelum', 'Jhang', 'Joharabad',
      'Kabirwala', 'Kahuta', 'Kalurkot', 'Kamalia', 'Kamoke', 'Kasur', 'Kehror Pacca',
      'Khanewal', 'Kharian', 'Khushab', 'Khanpur', 'Kot Addu', 'Kot Momin', 'Kot Radha Kishan',
      'Lahore', 'Layyah', 'Liaquatpur', 'Lodhran',
      'Mailsi', 'Manga Mandi', 'Mankera', 'Mandi Bahauddin', 'Mian Channu', 'Mianwali',
      'Minchinabad', 'Multan', 'Multan Cantonment', 'Muridke', 'Murree', 'Muzaffargarh',
      'Nankana Sahib', 'Narowal', 'Noorpur Thal', 'Nowshera Virkan',
      'Okara',
      'Pakpattan', 'Pasrur', 'Pattoki', 'Phalia', 'Phool Nagar', 'Piplan', 'Pirmahal',
      'Qila Didar Singh',
      'Rahimyar Khan', 'Raiwind', 'Rajana', 'Rajanpur', 'Rawalpindi', 'Rawat', 'Renala Khurd',
      'Sadiqabad', 'Sahiwal', 'Sambrial', 'Sammundri', 'Sargodha', 'Shakargarh', 'Shahpur',
      'Sheikhupura', 'Shujabad', 'Sialkot', 'Sillanwali',
      'Tandlianwali', 'Taunsa Sharif', 'Taxila', 'Toba Tek Singh',
      'Vehari',
      'Wah Cantonment', 'Wazirabad',
      'Yazman',
      'Zafarwal',
    ],
  },
  {
    state: 'Sindh',
    cities: [
      'Badin', 'Baldia Town', 'Bin Qasim',
      'Chhor', 'Clifton',
      'Dadu', 'Daharki', 'Digri', 'Diplo',
      'Gadap Town', 'Gambat', 'Garhi Khairo', 'Gharo', 'Ghotki', 'Golarchi', 'Gulberg',
      'Gulshan-e-Iqbal',
      'Hala', 'Hyderabad', 'Hyderabad Cantonment',
      'Jacobabad', 'Jati', 'Jhuddo', 'Johi',
      'Kambar Shahdadkot', 'Kandhkot', 'Kandiaro', 'Karachi', 'Kashmore', 'Kashmor',
      'Keamari', 'Keti Bandar', 'Khairpur', 'Khairpur Mirs', 'Khairpur Nathan Shah',
      'Korangi', 'Kot Ghulam Muhammad', 'Kotri', 'Kunri',
      'Landhi', 'Larkana', 'Latifabad', 'Liaquatabad', 'Lyari',
      'Malir', 'Manghopir', 'Matiari', 'Matli', 'Mehar', 'Mehrabpur', 'Mirpur Khas',
      'Mirpur Mathelo', 'Mirpur Sakro', 'Moro',
      'Naushahro Feroze', 'Naukot', 'Nawabshah', 'Nazimabad', 'North Karachi',
      'North Nazimabad',
      'Orangi Town',
      'Pano Aqil', 'Pithoro',
      'Qambar', 'Qasimabad',
      'Ranipur', 'Ratodero', 'Rohri',
      'Saddar', 'Sakrand', 'Sanghar', 'Sehwan', 'Shikarpur', 'Site Town', 'Sujawal', 'Sukkur',
      'Tando Adam', 'Tando Allahyar', 'Tando Bago', 'Tando Muhammad Khan', 'Thatta', 'Thul',
      'Ubauro', 'Umerkot',
      'Warah',
    ],
  },
  {
    state: 'Khyber Pakhtunkhwa',
    cities: [
      'Abbottabad', 'Akora Khattak', 'Alpuri',
      'Badaber', 'Bahrain', 'Balakot', 'Banda Daud Shah', 'Bannu', 'Bara', 'Barikot',
      'Battagram', 'Besham', 'Booni', 'Buner',
      'Chail', 'Chakdara', 'Chamkani', 'Charsadda', 'Chitral',
      'Daggar', 'Dargai', 'Dasu', 'Dera Ismail Khan', 'Doaba', 'Drosh',
      'Garam Chashma',
      'Hangu', 'Haripur', 'Havelian', 'Hayatabad', 'Hund',
      'Jamrud',
      'Kabal', 'Kalam', 'Karak', 'Katlang', 'Khazana', 'Khwaja Khela', 'Khwazakhela',
      'Kohat', 'Kumrat',
      'Ladha', 'Lakki Marwat', 'Landi Kotal', 'Lower Dir',
      'Madyan', 'Malakand', 'Mansehra', 'Mardan', 'Mastuj', 'Matani', 'Matta',
      'Mingora', 'Mir Ali', 'Miranshah',
      'Nowshera',
      'Oghi',
      'Pabbi', 'Pattan', 'Peshawar', 'Peshawar Cantonment',
      'Risalpur', 'Rustam',
      'Saidu Sharif', 'Sawaldher', 'Shabqadar', 'Shangla', 'Shinkiari', 'Swabi',
      'Swari',
      'Tank', 'Timergara', 'Topi', 'Tordher',
      'Upper Dir',
      'Wana', 'Warsak',
    ],
  },
  {
    state: 'Balochistan',
    cities: [
      'Awaran',
      'Barkhan', 'Bela', 'Besima', 'Bhag', 'Buleda', 'Bunji',
      'Chaman', 'Chattar',
      'Dalbandin', 'Darel', 'Dera Allah Yar', 'Dera Bugti', 'Duki',
      'Gadani', 'Gandava', 'Gwatar', 'Gwadar', 'Gulistan',
      'Harnai', 'Hoshab', 'Hub',
      'Jaffarabad', 'Jhal Magsi', 'Jiwani',
      'Kalat', 'Kashmore', 'Khaaran', 'Killa Abdullah', 'Kohlu', 'Kuchlak', 'Khuzdar',
      'Kharan',
      'Lasbela', 'Loralai', 'Loti', 'Lakhra',
      'Mach', 'Mand', 'Mashkel', 'Mastung', 'Musakhel',
      'Naal', 'Nasirabad', 'Nok Kundi', 'Nokundi', 'Nushki',
      'Ormara', 'Ornach',
      'Panjgur', 'Pasni', 'Pir Koh', 'Pishin',
      'Qila Saifullah', 'Quetta', 'Quetta Cantonment',
      'Sariab', 'Shahrag', 'Sibi', 'Sohbatpur', 'Sonmiani', 'Sui', 'Surab',
      'Taftan', 'Tump', 'Turbat',
      'Usta Muhammad', 'Uthal',
      'Wadh', 'Washuk', 'Winder',
      'Yazman',
      'Zehri', 'Zhob', 'Ziarat',
    ],
  },
  {
    state: 'Islamabad Capital Territory',
    cities: [
      'Bhara Kahu',
      'Golra',
      'Islamabad',
      'Nilore',
      'Rawat',
      'Shahzad Town', 'Sihala',
      'Tarlai', 'Tramri',
    ],
  },
  {
    state: 'Azad Jammu and Kashmir',
    cities: [
      'Athmuqam',
      'Bagh', 'Bhimber',
      'Chakswari', 'Charhoi', 'Chinari',
      'Dadyal', 'Domel', 'Dowarian',
      'Forward Kahuta',
      'Garhi Dupatta',
      'Hattian Bala', 'Haveli',
      'Kel', 'Khuiratta', 'Kotli', 'Kundal Shahi',
      'Leepa',
      'Mangla', 'Mirpur', 'Muzaffarabad',
      'Pallandri', 'Potha',
      'Rawalakot', 'Rakhchikri',
      'Samahni', 'Sehnsa', 'Sharda', 'Sudhnoti',
      'Trarkhal',
    ],
  },
  {
    state: 'Gilgit-Baltistan',
    cities: [
      'Aliabad', 'Astore',
      'Bunji',
      'Chatorkhand', 'Chilas',
      'Darel', 'Darkot', 'Deosai', 'Diamer',
      'Ghanche', 'Ghizer', 'Gilgit', 'Gulmit', 'Gupis',
      'Hunza',
      'Ishkoman',
      'Jaglot',
      'Kachura', 'Karimabad', 'Khaplu', 'Kharmang', 'Khunjerab',
      'Mendi', 'Minawar', 'Minimarg', 'Misgar',
      'Nagar', 'Nomal',
      'Passu', 'Phander',
      'Rondu', 'Roundu',
      'Satpara', 'Shigar', 'Skardu', 'Sost',
      'Tangir', 'Tolti',
      'Yasin',
    ],
  },
] as const

export const PAKISTAN_CITIES = PAKISTAN_STATE_CITIES.flatMap(group =>
  group.cities.map(city => ({ state: group.state, city }))
)